#!/bin/bash

echo "##### Performing common setup"
sudo apt-get update
# sudo apt-get -y upgrade
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils
sudo apt-get install -y vim tmux tshark

export PYENV_VERSION=3.5.2
pip3 install paho-mqtt aiocoap python_persistent_queue

echo "##### Performing specific setup"
whichnode=`hostname -s`

case "$whichnode" in
    "gatewaymqtt")
        echo "##### Performing gateway setup"
        # Install mosquitto
        sudo apt-get install -y software-properties-common python3-software-properties python-software-properties
        sudo apt-add-repository -y ppa:mosquitto-dev/mosquitto-ppa
        sudo apt-get update
        sudo apt-get install -y mosquitto mosquitto-clients
    ;;
    *)
        echo "Nothing to do";
esac
